# Generated by Django 4.0.10 on 2025-02-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('cup', 'cups'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('piece', 'pieces')], default='g', max_length=50),
        ),
    ]
