# Generated by Django 4.0.10 on 2025-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient_amount_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='link',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_minutes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
